# Generated by Django 2.0.5 on 2018-06-04 12:58

import ckeditor_uploader.fields
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='news-images/')),
                ('title', models.CharField(max_length=1000)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
