# Generated by Django 2.0.5 on 2018-05-18 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(max_length=250)),
                ('image_gold', models.CharField(max_length=250)),
                ('locale', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(blank=True, choices=[('wild', 'Wild'), ('standard', 'Standard')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Expansion'),
        ),
        migrations.AddField(
            model_name='card',
            name='player_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.PlayerClass'),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Rarity'),
        ),
    ]
