# Generated by Django 2.0.5 on 2018-05-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20180521_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
