# Generated by Django 2.0.5 on 2018-05-29 22:41

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_auto_20180529_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='images/'),
        ),
    ]
