# Generated by Django 2.0.5 on 2018-06-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_auto_20180602_0832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
